vich_uploader:
    db_driver: orm
    mappings:
        joueur_pic:
            uri_prefix: /images/joueurs
            upload_destination: '%kernel.project_dir%/public/images/joueurs'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        equipe_logo:
            uri_prefix: /images/equipes
            upload_destination: '%kernel.project_dir%/public/images/equipes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
